[workspace]
members = [
	"cli",
	"sdk",
	"xtask",
]

[workspace.dependencies]
anyhow = "1.0.69"
base64 = "0.21.0"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive", "string", "env"] }
futures = "0.3.26"
oauth2 = "4.3.0"
oxide-api = { path = "sdk" }
pretty_assertions = "1.3.0"
progenitor = { git = "https://github.com/oxidecomputer/progenitor", branch = "cli" }
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor", branch = "cli" }
rand = "0.8.5"
regress = "0.4.1"
reqwest = "0.11.14"
schemars = { version = "0.8.12", features = ["chrono", "uuid1"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serial_test = "1.0.0"
sha2 = "0.10.6"
tokio = { version = "1.24.2", features = ["full"] }
url = "2.3.1"
uuid = { version = "1.2.2", features = ["serde", "v4"] }

#[patch."https://github.com/oxidecomputer/progenitor"]
#progenitor = { path = "../progenitor/progenitor" }
#[patch."https://github.com/oxidecomputer/typify"]
#typify = { path = "../typify/typify" }
